org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.disableCompilerDaemon=false

android.useAndroidX=true
android.nonTransitiveRClass=true

# Compose Multiplatform
compose.kotlin.native.utils=true
