package com.d2m.app.ui.components

import com.d2m.app.ui.strings.AppLocale

/**
 * Direct Kotlin mirror of d2m_core_engine/app/taxonomy.py (and d2m_web's own
 * lib/taxonomy.js mirror of it) -- illustrative, not exhaustive, per that
 * file's own docstring. Kept in sync by hand, same as the other two copies.
 */
object Taxonomy {
    val RELIGIONS = listOf("Hindu", "Muslim", "Christian", "Sikh", "Jain", "Buddhist", "Parsi", "Other")

    val COMMUNITIES = listOf(
        "iyer", "iyengar", "brahmin_other", "gsb", "bengali_brahmin",
        "kashmiri_pandit", "saraswat", "nair", "menon", "ezhava", "nadar",
        "mudaliar", "pillai", "vellalar", "chettiar", "gounder", "reddy",
        "naidu", "kamma", "kapu", "velama", "vokkaliga", "lingayat",
        "bunt", "kayastha", "rajput", "jat", "gujjar", "yadav", "kurmi",
        "khatri", "agarwal", "baniya", "maratha", "patel", "sindhi",
        "punjabi_other", "bengali_other", "anglo_indian", "sc_st", "other",
    )

    val MARITAL_STATUSES = listOf("never_married", "divorced", "widowed", "annulled")
    val GENDERS = listOf("male", "female", "non_binary")
    val EDUCATION_LEVELS = listOf("high_school", "bachelors", "masters", "doctorate", "professional_degree")
    val PROFESSION_TIERS = listOf("student", "early_career", "mid_career", "senior", "business_owner", "not_working")
    val INCOME_BANDS = listOf("under_5l", "5l_10l", "10l_25l", "25l_50l", "50l_plus")

    val HOBBIES = listOf(
        "reading", "travel", "cooking", "fitness", "music", "movies", "hiking",
        "photography", "gaming", "volunteering", "sports", "dancing", "art", "yoga", "pets",
    )
    val LIFESTYLE_TAGS = listOf(
        "non_smoker", "smoker", "non_drinker", "social_drinker", "vegetarian",
        "non_vegetarian", "vegan", "wants_children", "open_on_children", "no_children_wanted",
    )
    val RELATIONSHIP_GOALS = listOf("marriage_ready", "marriage_within_a_year", "open_to_long_courtship")

    val BODY_TYPES = listOf("slim", "athletic", "average", "heavy")
    val HOROSCOPE_MATCH_PREFERENCES = listOf("required", "preferred", "not_required")
    val EMPLOYMENT_SECTORS = listOf("private", "government_psu", "business", "self_employed", "not_working")
    val FAMILY_TYPES = listOf("nuclear", "joint")
    val FAMILY_VALUES = listOf("traditional", "moderate", "liberal")
    val CITIZENSHIP_STATUSES = listOf("citizen", "permanent_resident", "work_visa", "student_visa", "other")

    // Display-ready values (proper nouns/codes), rendered as-is, no toLabel().
    val COMPLEXIONS = listOf("Very Fair", "Fair", "Wheatish", "Wheatish Brown", "Dark")
    val LANGUAGES = listOf(
        "Tamil", "Telugu", "Kannada", "Malayalam", "Hindi", "Marathi", "Gujarati",
        "Bengali", "Punjabi", "Urdu", "Odia", "Assamese", "Konkani", "Sindhi",
        "Kashmiri", "Maithili", "Bhojpuri", "Tulu", "Sanskrit", "Nepali", "English", "Other",
    )
    val GOTHRAMS = listOf(
        "Bharadwaja", "Kashyapa", "Vashishta", "Kaushika", "Atreya", "Vishwamitra",
        "Shrivatsa", "Gautama", "Agastya", "Koundinya", "Shandilya", "Harita",
        "Vatsa", "Angirasa", "Parashara", "Jamadagni", "Kutsa", "Sankriti",
        "Marichi", "Pulastya", "Bhrigu", "Other",
    )
    val SECTS = listOf(
        "Vadama", "Brahacharanam", "Vathima", "Ashtasahasram", "Vadadesha",
        "Vadakalai", "Thenkalai", "Smartha", "Madhwa", "Shaiva", "Vaishnava",
        "Not applicable", "Other",
    )
    val CURRENCIES = listOf("INR", "USD", "GBP", "EUR", "AED", "CAD", "AUD", "SGD")

    // -- AboutMeData picklists (About Me tab) -- mirrors the block of the
    // same name in app/taxonomy.py. Deliberately distinct from HOBBIES/
    // LIFESTYLE_TAGS/RELATIONSHIP_GOALS above -- those already back the
    // Preferences tab and matching_service's scoring; About Me doesn't
    // re-ask the same questions under new names.
    val FITNESS_ROUTINES = listOf("Never", "Occasionally", "Regularly", "Daily")
    val SLEEP_SCHEDULES = listOf("Early bird", "Night owl", "Flexible")
    val PET_PREFERENCES = listOf("Love pets & have one", "Love pets, none currently", "Not a pet person", "Allergic")
    val SOCIAL_ENERGIES = listOf("Introvert", "Extrovert", "Ambivert")
    val PARTNER_QUALITIES = listOf(
        "Kind", "Ambitious", "Family-oriented", "Good sense of humor", "Adventurous",
        "Supportive", "Well-settled", "Spiritual", "Good listener", "Confident", "Easy-going",
    )
    val CAREER_AFTER_MARRIAGE_OPTIONS = listOf("Continue working", "Open to pausing", "Flexible", "Prefer not to work")
    val LIVING_ARRANGEMENTS = listOf("With parents", "Independent/nuclear", "Flexible")
    val RELOCATION_PREFERENCES = listOf("Yes", "No", "Depends")
    val LOVE_LANGUAGES = listOf("Words of affirmation", "Acts of service", "Quality time", "Gifts", "Physical touch")
    val ABOUT_ME_PROMPTS = listOf(
        "A life goal of mine is…",
        "My friends would describe me as…",
        "I geek out on…",
        "My weekends usually look like…",
        "A fact that surprises people about me…",
        "My simple pleasures are…",
        "The way to my heart is…",
        "I'm currently obsessed with…",
    )

    // Tap-to-fill suggestions for the About Me tab's free-text fields --
    // UNLIKE every list above, these are NOT a closed set (the backend
    // fields stay plain free text, no validation) -- just saves typing for
    // the common case. Deliberately long ("I want an exhaustive list",
    // reported directly) -- the UI shows a short slice with a "show more"
    // expander rather than trimming the list itself. Mirrors d2m_web's
    // lib/taxonomy.js CUISINE_SUGGESTIONS / DESTINATION_SUGGESTIONS /
    // WHAT_MATTERS_MOST_SUGGESTIONS.
    val CUISINE_SUGGESTIONS = listOf(
        "North Indian", "South Indian", "Punjabi", "Gujarati", "Rajasthani", "Bengali",
        "Hyderabadi", "Chettinad", "Malabar", "Konkani", "Maharashtrian", "Goan",
        "Italian", "Thai", "Chinese", "Japanese", "Korean", "Vietnamese",
        "Mexican", "Mediterranean", "Lebanese", "Turkish", "Continental", "French",
        "Spanish", "Greek", "American", "BBQ & grill", "Street food", "Vegan / plant-based",
    )
    // Dream destination dropped this static list in favor of
    // CityAutocomplete's live Open-Meteo search (ChildProfileDialogScreen.kt)
    // -- "provide the same suggestion option as locations", reported
    // directly. No callers left; d2m_web's own DESTINATION_SUGGESTIONS was
    // removed the same way.
    val WHAT_MATTERS_MOST_SUGGESTIONS = listOf(
        "Kindness and honesty",
        "Shared values and mutual respect",
        "Great communication",
        "Ambition and drive",
        "A strong sense of family",
        "Humor and positivity",
        "Emotional maturity",
        "Loyalty and trust",
        "Being each other's best friend",
        "Growing together",
        "Financial responsibility",
        "Spiritual compatibility",
        "Supporting each other's dreams",
        "A partner who really listens",
        "Balancing career and family",
        "Respect for each other's families",
        "Adventure and shared experiences",
        "Patience and understanding",
    )

    private val ACRONYMS = mapOf("usa" to "USA", "uk" to "UK", "ncr" to "NCR")

    /**
     * Locale-aware: consults [HI_LABELS]/[TA_LABELS] (ported wholesale from
     * d2m_web's lib/taxonomyLabels.js -- see that file's own doc comment on
     * what's a real translation vs. a transliteration) first, falling back
     * to the English humanized form ("5l_10l" -> "5L - 10L"-ish) for any
     * value with no entry there, exactly mirroring taxonomy.js's own
     * toLabel(value, lang) fallback so a new/unlisted enum value never
     * renders blank in any locale.
     */
    fun toLabel(value: String, locale: AppLocale = AppLocale.EN): String {
        val dict = when (locale) {
            AppLocale.HI -> HI_LABELS
            AppLocale.TA -> TA_LABELS
            AppLocale.EN -> null
        }
        dict?.get(value)?.let { return it }
        return value.split("_").joinToString(" ") { part ->
            ACRONYMS[part] ?: part.replaceFirstChar { it.uppercase() }
        }
    }
}
private val HI_LABELS = mapOf(
    "Hindu" to "हिंदू",
    "Muslim" to "मुस्लिम",
    "Christian" to "ईसाई",
    "Sikh" to "सिख",
    "Jain" to "जैन",
    "Buddhist" to "बौद्ध",
    "Parsi" to "पारसी",
    "Other" to "अन्य",
    "iyer" to "अय्यर",
    "iyengar" to "अयंगार",
    "brahmin_other" to "ब्राह्मण (अन्य)",
    "gsb" to "जीएसबी",
    "bengali_brahmin" to "बंगाली ब्राह्मण",
    "kashmiri_pandit" to "कश्मीरी पंडित",
    "saraswat" to "सारस्वत",
    "nair" to "नायर",
    "menon" to "मेनन",
    "ezhava" to "एझवा",
    "nadar" to "नाडार",
    "mudaliar" to "मुदलियार",
    "pillai" to "पिल्लई",
    "vellalar" to "वेल्लालर",
    "chettiar" to "चेट्टियार",
    "gounder" to "गौंडर",
    "reddy" to "रेड्डी",
    "naidu" to "नायडू",
    "kamma" to "कम्मा",
    "kapu" to "कापू",
    "velama" to "वेलामा",
    "vokkaliga" to "वोक्कालिगा",
    "lingayat" to "लिंगायत",
    "bunt" to "बंट",
    "kayastha" to "कायस्थ",
    "rajput" to "राजपूत",
    "jat" to "जाट",
    "gujjar" to "गुज्जर",
    "yadav" to "यादव",
    "kurmi" to "कुर्मी",
    "khatri" to "खत्री",
    "agarwal" to "अग्रवाल",
    "baniya" to "बनिया",
    "maratha" to "मराठा",
    "patel" to "पटेल",
    "sindhi" to "सिंधी",
    "punjabi_other" to "पंजाबी (अन्य)",
    "bengali_other" to "बंगाली (अन्य)",
    "anglo_indian" to "एंग्लो-इंडियन",
    "sc_st" to "अनुसूचित जाति/जनजाति",
    "never_married" to "अविवाहित",
    "divorced" to "तलाकशुदा",
    "widowed" to "विधवा/विधुर",
    "annulled" to "रद्द विवाह",
    "male" to "पुरुष",
    "female" to "महिला",
    "non_binary" to "नॉन-बाइनरी",
    "high_school" to "हाई स्कूल",
    "bachelors" to "स्नातक",
    "masters" to "स्नातकोत्तर",
    "doctorate" to "डॉक्टरेट",
    "professional_degree" to "व्यावसायिक डिग्री",
    "student" to "छात्र",
    "early_career" to "शुरुआती करियर",
    "mid_career" to "मध्य करियर",
    "senior" to "वरिष्ठ",
    "business_owner" to "व्यवसाय स्वामी",
    "not_working" to "कार्यरत नहीं",
    "under_5l" to "5 लाख से कम",
    "5l_10l" to "5–10 लाख",
    "10l_25l" to "10–25 लाख",
    "25l_50l" to "25–50 लाख",
    "50l_plus" to "50 लाख से अधिक",
    "reading" to "पढ़ना",
    "travel" to "यात्रा",
    "cooking" to "खाना बनाना",
    "fitness" to "फिटनेस",
    "music" to "संगीत",
    "movies" to "फ़िल्में",
    "hiking" to "हाइकिंग",
    "photography" to "फोटोग्राफी",
    "gaming" to "गेमिंग",
    "volunteering" to "स्वयंसेवा",
    "sports" to "खेल",
    "dancing" to "नृत्य",
    "art" to "कला",
    "yoga" to "योग",
    "pets" to "पालतू जानवर",
    "non_smoker" to "धूम्रपान नहीं करते",
    "smoker" to "धूम्रपान करते हैं",
    "non_drinker" to "शराब नहीं पीते",
    "social_drinker" to "कभी-कभार शराब",
    "vegetarian" to "शाकाहारी",
    "non_vegetarian" to "मांसाहारी",
    "vegan" to "वीगन",
    "wants_children" to "बच्चे चाहते हैं",
    "open_on_children" to "बच्चों पर खुले विचार",
    "no_children_wanted" to "बच्चे नहीं चाहते",
    "Smoking" to "धूम्रपान",
    "Drinking" to "शराब",
    "Diet" to "आहार",
    "Children" to "बच्चे",
    "marriage_ready" to "विवाह हेतु तैयार",
    "marriage_within_a_year" to "एक वर्ष में विवाह",
    "open_to_long_courtship" to "लंबी प्रतीक्षा के लिए तैयार",
    "slim" to "दुबला",
    "athletic" to "एथलेटिक",
    "average" to "औसत",
    "heavy" to "भारी",
    "required" to "आवश्यक",
    "preferred" to "वरीयता",
    "not_required" to "आवश्यक नहीं",
    "private" to "निजी क्षेत्र",
    "government_psu" to "सरकारी/पीएसयू",
    "business" to "व्यवसाय",
    "self_employed" to "स्वरोज़गार",
    "nuclear" to "एकल परिवार",
    "joint" to "संयुक्त परिवार",
    "traditional" to "पारंपरिक",
    "moderate" to "मध्यम",
    "liberal" to "उदार",
    "citizen" to "नागरिक",
    "permanent_resident" to "स्थायी निवासी",
    "work_visa" to "वर्क वीज़ा",
    "student_visa" to "स्टूडेंट वीज़ा",
    "Very Fair" to "अत्यंत गोरा",
    "Fair" to "गोरा",
    "Wheatish" to "गेहुंआ",
    "Wheatish Brown" to "गेहुंआ भूरा",
    "Dark" to "सांवला",
    "Tamil" to "तमिल",
    "Telugu" to "तेलुगु",
    "Kannada" to "कन्नड़",
    "Malayalam" to "मलयालम",
    "Hindi" to "हिंदी",
    "Marathi" to "मराठी",
    "Gujarati" to "गुजराती",
    "Bengali" to "बंगाली",
    "Punjabi" to "पंजाबी",
    "Urdu" to "उर्दू",
    "Odia" to "उड़िया",
    "Assamese" to "असमिया",
    "Konkani" to "कोंकणी",
    "Sindhi" to "सिंधी",
    "Kashmiri" to "कश्मीरी",
    "Maithili" to "मैथिली",
    "Bhojpuri" to "भोजपुरी",
    "Tulu" to "तुलु",
    "Sanskrit" to "संस्कृत",
    "Nepali" to "नेपाली",
    "English" to "अंग्रेज़ी",
    "Bharadwaja" to "भारद्वाज",
    "Kashyapa" to "कश्यप",
    "Vashishta" to "वशिष्ठ",
    "Kaushika" to "कौशिक",
    "Atreya" to "आत्रेय",
    "Vishwamitra" to "विश्वामित्र",
    "Shrivatsa" to "श्रीवत्स",
    "Gautama" to "गौतम",
    "Agastya" to "अगस्त्य",
    "Koundinya" to "कौण्डिन्य",
    "Shandilya" to "शांडिल्य",
    "Harita" to "हरित",
    "Vatsa" to "वत्स",
    "Angirasa" to "आंगिरस",
    "Parashara" to "पराशर",
    "Jamadagni" to "जमदग्नि",
    "Kutsa" to "कुत्स",
    "Sankriti" to "सांकृति",
    "Marichi" to "मारीचि",
    "Pulastya" to "पुलस्त्य",
    "Bhrigu" to "भृगु",
    "Vadama" to "वडमा",
    "Brahacharanam" to "ब्रहचरणम्",
    "Vathima" to "वथिमा",
    "Ashtasahasram" to "अष्टसहस्रम्",
    "Vadadesha" to "वडदेश",
    "Vadakalai" to "वडकलै",
    "Thenkalai" to "तेनकलै",
    "Smartha" to "स्मार्त",
    "Madhwa" to "माध्व",
    "Shaiva" to "शैव",
    "Vaishnava" to "वैष्णव",
    "Not applicable" to "लागू नहीं",
    "Never" to "कभी नहीं",
    "Occasionally" to "कभी-कभी",
    "Regularly" to "नियमित रूप से",
    "Daily" to "रोज़ाना",
    "Early bird" to "जल्दी उठने वाला",
    "Night owl" to "रात में जागने वाला",
    "Flexible" to "लचीला",
    "Love pets & have one" to "पालतू जानवर पसंद और पास में है",
    "Love pets, none currently" to "पालतू जानवर पसंद, पर अभी नहीं है",
    "Not a pet person" to "पालतू जानवर पसंद नहीं",
    "Allergic" to "एलर्जी है",
    "Introvert" to "अंतर्मुखी",
    "Extrovert" to "बहिर्मुखी",
    "Ambivert" to "दोनों",
    "Kind" to "दयालु",
    "Ambitious" to "महत्वाकांक्षी",
    "Family-oriented" to "परिवार-केंद्रित",
    "Good sense of humor" to "अच्छी हास्य भावना",
    "Adventurous" to "साहसी",
    "Supportive" to "सहयोगी",
    "Well-settled" to "अच्छी तरह से स्थापित",
    "Spiritual" to "आध्यात्मिक",
    "Good listener" to "अच्छा श्रोता",
    "Confident" to "आत्मविश्वासी",
    "Easy-going" to "सहज स्वभाव",
    "Continue working" to "काम जारी रखना",
    "Open to pausing" to "रुकने के लिए तैयार",
    "Prefer not to work" to "काम न करना पसंद",
    "With parents" to "माता-पिता के साथ",
    "Independent/nuclear" to "स्वतंत्र/एकल",
    "Yes" to "हाँ",
    "No" to "नहीं",
    "Depends" to "निर्भर करता है",
    "Words of affirmation" to "प्रशंसा के शब्द",
    "Acts of service" to "सेवा के कार्य",
    "Quality time" to "गुणवत्तापूर्ण समय",
    "Gifts" to "उपहार",
    "Physical touch" to "शारीरिक स्पर्श",
    "A life goal of mine is…" to "मेरा एक जीवन लक्ष्य है…",
    "My friends would describe me as…" to "मेरे दोस्त मुझे ऐसे बताएंगे…",
    "I geek out on…" to "मुझे इस पर जुनून है…",
    "My weekends usually look like…" to "मेरे सप्ताहांत आमतौर पर ऐसे होते हैं…",
    "A fact that surprises people about me…" to "मेरे बारे में एक चौंकाने वाली बात…",
    "My simple pleasures are…" to "मेरी छोटी खुशियाँ हैं…",
    "The way to my heart is…" to "मेरे दिल तक पहुँचने का रास्ता है…",
    "I'm currently obsessed with…" to "आजकल मुझे इसका शौक है…",
    "North Indian" to "उत्तर भारतीय",
    "South Indian" to "दक्षिण भारतीय",
    "Rajasthani" to "राजस्थानी",
    "Hyderabadi" to "हैदराबादी",
    "Chettinad" to "चेट्टिनाड",
    "Malabar" to "मालाबार",
    "Maharashtrian" to "महाराष्ट्रीयन",
    "Goan" to "गोवन",
    "Italian" to "इतालवी",
    "Thai" to "थाई",
    "Chinese" to "चाइनीज़",
    "Japanese" to "जापानी",
    "Korean" to "कोरियाई",
    "Vietnamese" to "वियतनामी",
    "Mexican" to "मैक्सिकन",
    "Mediterranean" to "भूमध्यसागरीय",
    "Lebanese" to "लेबनानी",
    "Turkish" to "तुर्की",
    "Continental" to "कॉन्टिनेंटल",
    "French" to "फ्रेंच",
    "Spanish" to "स्पेनिश",
    "Greek" to "ग्रीक",
    "American" to "अमेरिकी",
    "BBQ & grill" to "बीबीक्यू और ग्रिल",
    "Street food" to "स्ट्रीट फूड",
    "Vegan / plant-based" to "वीगन / पौध-आधारित",
    "Kindness and honesty" to "दयालुता और ईमानदारी",
    "Shared values and mutual respect" to "साझा मूल्य और आपसी सम्मान",
    "Great communication" to "बेहतरीन संवाद",
    "Ambition and drive" to "महत्वाकांक्षा और जोश",
    "A strong sense of family" to "परिवार के प्रति गहरा लगाव",
    "Humor and positivity" to "हास्य और सकारात्मकता",
    "Emotional maturity" to "भावनात्मक परिपक्वता",
    "Loyalty and trust" to "वफ़ादारी और विश्वास",
    "Being each other's best friend" to "एक-दूसरे के सबसे अच्छे दोस्त होना",
    "Growing together" to "साथ में आगे बढ़ना",
    "Financial responsibility" to "आर्थिक ज़िम्मेदारी",
    "Spiritual compatibility" to "आध्यात्मिक अनुकूलता",
    "Supporting each other's dreams" to "एक-दूसरे के सपनों का साथ देना",
    "A partner who really listens" to "वह साथी जो सच में सुनता हो",
    "Balancing career and family" to "करियर और परिवार में संतुलन",
    "Respect for each other's families" to "एक-दूसरे के परिवार का सम्मान",
    "Adventure and shared experiences" to "रोमांच और साझा अनुभव",
    "Patience and understanding" to "धैर्य और समझ",
)

private val TA_LABELS = mapOf(
    "Hindu" to "இந்து",
    "Muslim" to "முஸ்லிம்",
    "Christian" to "கிறிஸ்தவர்",
    "Sikh" to "சீக்கியர்",
    "Jain" to "ஜைனர்",
    "Buddhist" to "பௌத்தர்",
    "Parsi" to "பார்சி",
    "Other" to "மற்றவை",
    "iyer" to "ஐயர்",
    "iyengar" to "ஐயங்கார்",
    "brahmin_other" to "பிராமணர் (மற்றவை)",
    "gsb" to "ஜி.எஸ்.பி",
    "bengali_brahmin" to "வங்காள பிராமணர்",
    "kashmiri_pandit" to "காஷ்மீரி பண்டிட்",
    "saraswat" to "சாரஸ்வத்",
    "nair" to "நாயர்",
    "menon" to "மேனன்",
    "ezhava" to "ஈழவா",
    "nadar" to "நாடார்",
    "mudaliar" to "முதலியார்",
    "pillai" to "பிள்ளை",
    "vellalar" to "வேளாளர்",
    "chettiar" to "செட்டியார்",
    "gounder" to "கவுண்டர்",
    "reddy" to "ரெட்டி",
    "naidu" to "நாயுடு",
    "kamma" to "காம்மா",
    "kapu" to "காபு",
    "velama" to "வெலமா",
    "vokkaliga" to "வொக்கலிகா",
    "lingayat" to "லிங்காயத்",
    "bunt" to "பண்ட்",
    "kayastha" to "காயஸ்த",
    "rajput" to "ராஜ்புத்",
    "jat" to "ஜாட்",
    "gujjar" to "குஜ்ஜர்",
    "yadav" to "யாதவ்",
    "kurmi" to "குர்மி",
    "khatri" to "காத்ரி",
    "agarwal" to "அகர்வால்",
    "baniya" to "பனியா",
    "maratha" to "மராத்தா",
    "patel" to "படேல்",
    "sindhi" to "சிந்தி",
    "punjabi_other" to "பஞ்சாபி (மற்றவை)",
    "bengali_other" to "வங்காளி (மற்றவை)",
    "anglo_indian" to "ஆங்கிலோ-இந்தியர்",
    "sc_st" to "பட்டியல் சாதி/பழங்குடி",
    "never_married" to "திருமணமாகாதவர்",
    "divorced" to "விவாகரத்தானவர்",
    "widowed" to "விதவை/விதவன்",
    "annulled" to "ரத்து செய்யப்பட்ட திருமணம்",
    "male" to "ஆண்",
    "female" to "பெண்",
    "non_binary" to "நான்-பைனரி",
    "high_school" to "உயர்நிலைப் பள்ளி",
    "bachelors" to "இளங்கலை",
    "masters" to "முதுகலை",
    "doctorate" to "முனைவர் பட்டம்",
    "professional_degree" to "தொழில்முறை பட்டம்",
    "student" to "மாணவர்",
    "early_career" to "தொழில் தொடக்கம்",
    "mid_career" to "நடுநிலை தொழில்",
    "senior" to "மூத்த நிலை",
    "business_owner" to "வணிக உரிமையாளர்",
    "not_working" to "பணியில் இல்லை",
    "under_5l" to "5 லட்சத்திற்கும் குறைவு",
    "5l_10l" to "5–10 லட்சம்",
    "10l_25l" to "10–25 லட்சம்",
    "25l_50l" to "25–50 லட்சம்",
    "50l_plus" to "50 லட்சத்திற்கும் மேல்",
    "reading" to "வாசிப்பு",
    "travel" to "பயணம்",
    "cooking" to "சமையல்",
    "fitness" to "உடற்பயிற்சி",
    "music" to "இசை",
    "movies" to "திரைப்படங்கள்",
    "hiking" to "மலையேற்றம்",
    "photography" to "புகைப்படம்",
    "gaming" to "விளையாட்டுகள்",
    "volunteering" to "தன்னார்வத் தொண்டு",
    "sports" to "விளையாட்டு",
    "dancing" to "நடனம்",
    "art" to "கலை",
    "yoga" to "யோகா",
    "pets" to "செல்லப்பிராணிகள்",
    "non_smoker" to "புகைபிடிக்காதவர்",
    "smoker" to "புகைபிடிப்பவர்",
    "non_drinker" to "மது அருந்தாதவர்",
    "social_drinker" to "எப்போதாவது அருந்துபவர்",
    "vegetarian" to "சைவம்",
    "non_vegetarian" to "அசைவம்",
    "vegan" to "வீகன்",
    "wants_children" to "குழந்தைகள் வேண்டும்",
    "open_on_children" to "குழந்தைகள் விஷயத்தில் நெகிழ்வு",
    "no_children_wanted" to "குழந்தைகள் வேண்டாம்",
    "Smoking" to "புகைபிடித்தல்",
    "Drinking" to "மது அருந்துதல்",
    "Diet" to "உணவுமுறை",
    "Children" to "குழந்தைகள்",
    "marriage_ready" to "திருமணத்திற்கு தயார்",
    "marriage_within_a_year" to "ஓராண்டில் திருமணம்",
    "open_to_long_courtship" to "நீண்ட காலம் பழகத் தயார்",
    "slim" to "மெலிந்த",
    "athletic" to "விளையாட்டு உடல்வாகு",
    "average" to "சராசரி",
    "heavy" to "பருமனான",
    "required" to "அவசியம்",
    "preferred" to "விருப்பம்",
    "not_required" to "அவசியமில்லை",
    "private" to "தனியார் துறை",
    "government_psu" to "அரசு/அரசு நிறுவனம்",
    "business" to "வணிகம்",
    "self_employed" to "சுயதொழில்",
    "nuclear" to "தனிக் குடும்பம்",
    "joint" to "கூட்டுக் குடும்பம்",
    "traditional" to "பாரம்பரியமான",
    "moderate" to "மிதமான",
    "liberal" to "தாராள மனப்பான்மை",
    "citizen" to "குடிமகன்",
    "permanent_resident" to "நிரந்தர குடியிருப்பாளர்",
    "work_visa" to "பணி விசா",
    "student_visa" to "மாணவர் விசா",
    "Very Fair" to "மிகவும் வெண்மை",
    "Fair" to "வெண்மை",
    "Wheatish" to "கோதுமை நிறம்",
    "Wheatish Brown" to "கோதுமை பழுப்பு",
    "Dark" to "கருப்பு",
    "Tamil" to "தமிழ்",
    "Telugu" to "தெலுங்கு",
    "Kannada" to "கன்னடம்",
    "Malayalam" to "மலையாளம்",
    "Hindi" to "ஹிந்தி",
    "Marathi" to "மராத்தி",
    "Gujarati" to "குஜராத்தி",
    "Bengali" to "வங்காளம்",
    "Punjabi" to "பஞ்சாபி",
    "Urdu" to "உருது",
    "Odia" to "ஒடியா",
    "Assamese" to "அசாமியம்",
    "Konkani" to "கொங்கணி",
    "Sindhi" to "சிந்தி",
    "Kashmiri" to "காஷ்மீரி",
    "Maithili" to "மைதிலி",
    "Bhojpuri" to "போஜ்புரி",
    "Tulu" to "துளு",
    "Sanskrit" to "சமஸ்கிருதம்",
    "Nepali" to "நேபாளி",
    "English" to "ஆங்கிலம்",
    "Bharadwaja" to "பரத்வாஜ",
    "Kashyapa" to "கஸ்யப",
    "Vashishta" to "வசிஷ்ட",
    "Kaushika" to "கௌசிக",
    "Atreya" to "அத்ரேய",
    "Vishwamitra" to "விஸ்வாமித்ர",
    "Shrivatsa" to "ஸ்ரீவத்ஸ",
    "Gautama" to "கெளதம",
    "Agastya" to "அகத்தியர்",
    "Koundinya" to "கெளண்டின்ய",
    "Shandilya" to "சாண்டில்ய",
    "Harita" to "ஹரித",
    "Vatsa" to "வத்ஸ",
    "Angirasa" to "ஆங்கிரச",
    "Parashara" to "பராசர",
    "Jamadagni" to "ஜமதக்னி",
    "Kutsa" to "குத்ஸ",
    "Sankriti" to "சாங்க்ரிதி",
    "Marichi" to "மரீசி",
    "Pulastya" to "புலஸ்தியர்",
    "Bhrigu" to "பிருகு",
    "Vadama" to "வடமா",
    "Brahacharanam" to "பிரஹசரணம்",
    "Vathima" to "வத்திமா",
    "Ashtasahasram" to "அஷ்டசகஸ்ரம்",
    "Vadadesha" to "வடதேசம்",
    "Vadakalai" to "வடகலை",
    "Thenkalai" to "தென்கலை",
    "Smartha" to "ஸ்மார்த்தா",
    "Madhwa" to "மாத்வா",
    "Shaiva" to "சைவம்",
    "Vaishnava" to "வைணவம்",
    "Not applicable" to "பொருந்தாது",
    "Never" to "ஒருபோதும் இல்லை",
    "Occasionally" to "எப்போதாவது",
    "Regularly" to "தொடர்ந்து",
    "Daily" to "தினமும்",
    "Early bird" to "காலையில் எழுபவர்",
    "Night owl" to "இரவில் விழித்திருப்பவர்",
    "Flexible" to "நெகிழ்வானது",
    "Love pets & have one" to "செல்லப்பிராணிகளை விரும்பி ஒன்று வைத்துள்ளேன்",
    "Love pets, none currently" to "செல்லப்பிராணிகளை விரும்புவேன், தற்போது இல்லை",
    "Not a pet person" to "செல்லப்பிராணி பிடிக்காதவர்",
    "Allergic" to "ஒவ்வாமை உள்ளது",
    "Introvert" to "உள்முக சிந்தனையாளர்",
    "Extrovert" to "வெளிமுக சிந்தனையாளர்",
    "Ambivert" to "இரண்டும் கலந்தவர்",
    "Kind" to "கருணையுள்ள",
    "Ambitious" to "லட்சிய வேட்கை கொண்ட",
    "Family-oriented" to "குடும்ப நலன் கருதும்",
    "Good sense of humor" to "நகைச்சுவை உணர்வு",
    "Adventurous" to "சாகசம் விரும்பும்",
    "Supportive" to "ஆதரவளிக்கும்",
    "Well-settled" to "நல்ல முறையில் குடியேறியவர்",
    "Spiritual" to "ஆன்மீகம் சார்ந்த",
    "Good listener" to "நன்கு கேட்பவர்",
    "Confident" to "தன்னம்பிக்கையுள்ள",
    "Easy-going" to "எளிதில் பழகக்கூடிய",
    "Continue working" to "வேலையைத் தொடர்வது",
    "Open to pausing" to "இடைநிறுத்தத்திற்கு தயார்",
    "Prefer not to work" to "வேலை செய்ய விரும்பாதது",
    "With parents" to "பெற்றோருடன்",
    "Independent/nuclear" to "தனித்தனி/தனிக் குடும்பம்",
    "Yes" to "ஆம்",
    "No" to "இல்லை",
    "Depends" to "சூழ்நிலையைப் பொறுத்து",
    "Words of affirmation" to "உற்சாக வார்த்தைகள்",
    "Acts of service" to "சேவை செயல்கள்",
    "Quality time" to "தரமான நேரம்",
    "Gifts" to "பரிசுகள்",
    "Physical touch" to "உடல் தொடுகை",
    "A life goal of mine is…" to "எனது வாழ்க்கை இலக்கு…",
    "My friends would describe me as…" to "என் நண்பர்கள் என்னை இப்படி வர்ணிப்பார்கள்…",
    "I geek out on…" to "நான் இதில் ஆர்வமுடன் ஈடுபடுவேன்…",
    "My weekends usually look like…" to "என் வார இறுதி நாட்கள் பொதுவாக இப்படி இருக்கும்…",
    "A fact that surprises people about me…" to "என்னைப் பற்றி ஆச்சரியப்படுத்தும் ஒரு உண்மை…",
    "My simple pleasures are…" to "என் சிறிய மகிழ்ச்சிகள்…",
    "The way to my heart is…" to "என் மனதை வெல்லும் வழி…",
    "I'm currently obsessed with…" to "தற்போது எனக்கு பெரிதும் பிடித்திருப்பது…",
    "North Indian" to "வட இந்திய",
    "South Indian" to "தென் இந்திய",
    "Rajasthani" to "ராஜஸ்தானி",
    "Hyderabadi" to "ஹைதராபாதி",
    "Chettinad" to "செட்டிநாடு",
    "Malabar" to "மலபார்",
    "Maharashtrian" to "மகாராஷ்டிர",
    "Goan" to "கோவான்",
    "Italian" to "இத்தாலிய",
    "Thai" to "தாய்",
    "Chinese" to "சீன",
    "Japanese" to "ஜப்பானிய",
    "Korean" to "கொரிய",
    "Vietnamese" to "வியட்நாமிய",
    "Mexican" to "மெக்சிகன்",
    "Mediterranean" to "மத்தியதரைக் கடல்",
    "Lebanese" to "லெபனான்",
    "Turkish" to "துருக்கிய",
    "Continental" to "கான்டினென்டல்",
    "French" to "பிரெஞ்சு",
    "Spanish" to "ஸ்பானிஷ்",
    "Greek" to "கிரேக்க",
    "American" to "அமெரிக்க",
    "BBQ & grill" to "பார்பிக்யூ & கிரில்",
    "Street food" to "தெரு உணவு",
    "Vegan / plant-based" to "வீகன் / தாவர அடிப்படை",
    "Kindness and honesty" to "கருணையும் நேர்மையும்",
    "Shared values and mutual respect" to "பகிரப்பட்ட விழுமியங்களும் பரஸ்பர மரியாதையும்",
    "Great communication" to "சிறந்த தொடர்பு",
    "Ambition and drive" to "லட்சியமும் உந்துசக்தியும்",
    "A strong sense of family" to "குடும்பத்தின் மீதான ஆழ்ந்த பற்று",
    "Humor and positivity" to "நகைச்சுவையும் நேர்மறை மனப்பான்மையும்",
    "Emotional maturity" to "உணர்ச்சி முதிர்ச்சி",
    "Loyalty and trust" to "விசுவாசமும் நம்பிக்கையும்",
    "Being each other's best friend" to "ஒருவருக்கொருவர் சிறந்த நண்பராக இருப்பது",
    "Growing together" to "ஒன்றாக வளர்வது",
    "Financial responsibility" to "நிதிப் பொறுப்பு",
    "Spiritual compatibility" to "ஆன்மீக இணக்கம்",
    "Supporting each other's dreams" to "ஒருவர் கனவுகளுக்கு மற்றவர் ஆதரவு",
    "A partner who really listens" to "உண்மையாகக் கேட்கும் துணை",
    "Balancing career and family" to "தொழிலுக்கும் குடும்பத்திற்கும் இடையிலான சமநிலை",
    "Respect for each other's families" to "ஒருவர் குடும்பத்தை மற்றவர் மதிப்பது",
    "Adventure and shared experiences" to "சாகசமும் பகிரப்பட்ட அனுபவங்களும்",
    "Patience and understanding" to "பொறுமையும் புரிதலும்",
)
